### ISSUE TITLE
Shift calculator parameters should be persisted between visits

### ISSUE THREAD

**Issue by natbat** [natbat/pillarpointstewards#129]
from Leslie: "When I first entered as manager, the tide and all the parameters on the right were back to the default, though it saved each shift edit. I had thought we changed it during our call. So then I changed it back again to 0.5 maximum low tide on weekday and weekend, with 105 minutes shift before and after, but it reverted back to the default again after I popped over to the shift signup page. Could there be a SAVE button to save the shift parameters?"

**Comment by simonw** [comment]
I'm going to add a column to the `teams` table that stores the JSON version of those settings, updated on every call to the API.
