### ISSUE TITLE
The Agenda View Of Shifts for Duxbury gives Pillar Point shifts, and they are not in date order.

### ISSUE THREAD

**Issue by natbat** [natbat/pillarpointstewards#133]

**Comment by simonw** [comment]
I'm seeing different information on these two pages:
- https://www.tidepoolstewards.com/programs/pillar-point/shifts/
- https://www.tidepoolstewards.com/programs/duxbury/shifts/

We should default this page to only show upcoming shifts and have a separate page or tab for past shifts.

**Comment by simonw** [comment]
Turns out the sort order is unspecified:

https://github.com/natbat/pillarpointstewards/blob/29ebd7cf5d8062d0dc1723e5aa1888cac6d7b3c4/pillarpointstewards/shifts/views.py#L210-L220
