### ISSUE TITLE
Weather needs to be more reliable and differ between locations and have a disclaimer (please verify the weather with your favorite weather provider)

### ISSUE THREAD

**Issue by natbat** [natbat/pillarpointstewards#141]

**Comment by simonw** [comment]
Weather is currently hard-coded to a specific location:

https://github.com/natbat/pillarpointstewards/blob/28a40edbcdd4438a1e7b54917d9afaeb92895e3b/pillarpointstewards/weather/views.py#L8-L18

**Comment by simonw** [comment]
Need to be careful of rate limits while automating this. I'm going to use a similar pattern to:
- #257

But with a sleep.

**Comment by simonw** [comment]
Forecast isn't yet tied to a location:

https://github.com/natbat/pillarpointstewards/blob/56273dcf3964a76e0d311ab2e776ba06990b4822/pillarpointstewards/weather/models.py#L6-L27

**Comment by simonw** [comment]
https://www.tidepoolstewards.com/admin/weather/forecast/ before running the new workflow:

![CleanShot 2024-10-31 at 15 04 25@2x](https://github.com/user-attachments/assets/7d6f468c-8418-41a1-9e8d-b002c3fb2f91)

After:

![CleanShot 2024-10-31 at 15 06 15@2x](https://github.com/user-attachments/assets/53c84754-2965-46c6-831a-2310755a6003)
