### ISSUE TITLE
Include Low tide elevation on shift manager page

### ISSUE THREAD

**Issue by natbat** [natbat/pillarpointstewards#152]
From Leslie "Would it be possible to include the low tide elevation for each shift on the manger page? I see that you have it listed in each of the shift signup pages."

**Comment by simonw** [comment]
This is in the pattern portfolio: https://www.tidepoolstewards.com/patterns/

![CleanShot 2023-11-03 at 14 46 22@2x](https://github.com/natbat/pillarpointstewards/assets/9599/7dc87bd9-3628-4dff-b7a8-565f8cfbd83b)

But not currently in the implemented calendar:

https://www.tidepoolstewards.com/programs/pillar-point/manage-shifts/

<img width="825" alt="CleanShot 2023-11-03 at 14 46 55@2x" src="https://github.com/natbat/pillarpointstewards/assets/9599/9235c3db-e09f-473c-9a24-40f6df36f454">

**Comment by simonw** [comment]
Template: https://github.com/natbat/pillarpointstewards/blob/e75b4b642331a5884ec2bd44cd983919364aac45/pillarpointstewards/templates/_calculator_shift.html#L12

Looks like that should be `{% if shift.lowest_tide %}`.

**Comment by simonw** [comment]
Fixed:

<img width="806" alt="CleanShot 2023-11-03 at 14 49 57@2x" src="https://github.com/natbat/pillarpointstewards/assets/9599/5a5720fe-afae-4359-9965-7f5b51ac3164">
