### ISSUE TITLE
Mechanism for filing shift reports on shift pages

### ISSUE THREAD

**Issue by simonw** [natbat/pillarpointstewards#154]

**Comment by simonw** [comment]
The initial version of this will be a textarea that saves effectively a comment on a shift.

**Comment by simonw** [comment]
![CleanShot 2024-02-09 at 10 24 36@2x](https://github.com/natbat/pillarpointstewards/assets/9599/ba5ceb8c-d195-4652-9c1a-e41ac024718c)

**Comment by simonw** [comment]
For this preview anyone can see them if they exist, but only site staff can add them.

**Comment by natbat** [comment]
<img width="639" alt="Screen Shot 2024-02-09 at 12 27 01 PM" src="https://github.com/natbat/pillarpointstewards/assets/72973/295560cf-d6a0-45ef-a5d8-c599ab12dc51">

**Comment by simonw** [comment]
Now live!
