### ISSUE TITLE
Center shifts on lowest tide point in that curve with the shift buffer either side

### ISSUE THREAD

**Issue by natbat** [natbat/pillarpointstewards#2]
Goal here is that on any day the shift lasts for twice the buffer (buffer probably will be 1.5 hours, so a 3 hour total shift) centered around the lowest tide of that day (that is below the specified threshold - some days will have no shifts at all).

Stretch goal: 11th September has two low tides, we would like to get two shifts on that day.

**Comment by simonw** [comment]
Work on this is happening in this v2 notebook: https://observablehq.com/@natbat/tidepool-shift-calculator-v2

**Comment by simonw** [comment]
OK I think this does it: https://observablehq.com/compare/87c12e580f6434a1@331...87c12e580f6434a1@354

**Comment by simonw** [comment]
Needs manual QA.
