### ISSUE TITLE
Shift calendar + let people assign themselves to shifts

### ISSUE THREAD

**Issue by simonw** [natbat/pillarpointstewards#23]

**Comment by natbat** [comment]
<img width="600" alt="Screen Shot 2022-03-30 at 1 52 53 PM" src="https://user-images.githubusercontent.com/72973/160928970-1c7c92d4-f0a9-40a1-a691-4b8da223475a.png">

always choose the lowest tide shift that day

if you click on a day that has a shift on it:

if it is AVAILABLE ot PARTFULL: "would you like to sign up to the shift on the 12th March between 10:05 and 4:45pm?"

If it is FULL "There are 5 people scheduled on this shift already, would you also like to sign up to the shift on the 12th March between 10:05 and 4:45pm?"

If it is yours then "you are signed up to the shift on the 12th March between 10:05 and 4:45pm, would you like to cancel your shift?"

**Comment by simonw** [comment]
I'm going to have it always start by showing this current month and the next three months.

**Comment by simonw** [comment]
Tiny bit ugly but it will work for the first version:

`confirm("There are 5 people scheduled on this shift already, would you also like to sign up to the shift on the 12th March between 10:05 and 4:45pm?")`

<img width="409" alt="image" src="https://user-images.githubusercontent.com/9599/160931048-c50d2443-866a-40a9-a211-8f1597076972.png">

**Comment by simonw** [comment]
TIL: https://til.simonwillison.net/python/calendar-weeks - using `calendar` from Python standard library.

**Comment by simonw** [comment]
Here are the CSS classes I need to apply:
```html
    <tr>
        <td class="shiftday available"><a href="#">4<span class="context-text">th April, shift is between</span> <span class="shifttime">10am-2pm</span></a></td>
        <td class="noshift">5<span class="context-text">th April</span></td>
        <td class="noshift">6<span class="context-text">th April</span></td>
        <td class="shiftday partfull"><a href="#">7<span class="context-text">th April, shift is between</span> <span class="shifttime">10am-2pm</span></a></td>
        <td class="noshift">8<span class="context-text">th April</span></td>
        <td class="weekend noshift">9<span class="context-text">th April</span></td>
        <td class="weekend noshift">10<span class="context-text">th April</span></td>
    </tr>
```

**Comment by simonw** [comment]
Need to remove the Ajax but that's a separate issue:
- #46
