### ISSUE TITLE
Stop showing past shifts as if they were upcoming

### ISSUE THREAD

**Issue by natbat** [natbat/pillarpointstewards#43]
Shifts that have an END TIME past the current time/date should appear at the bottom of the page underneith the calendar

**Comment by simonw** [comment]
I see this when I log in at the moment:

![CleanShot 2022-05-06 at 14 37 46](https://user-images.githubusercontent.com/9599/167219755-2e1ace15-6c66-4c60-a177-06cb5a6df629.png)

It shouldn't be showing the month of April calendar, and it shouldn't show my upcoming shifts that I have already done.

I'm still going to show your upcoming shift if it happened today - I'll treat "upcoming" as anything from tomorrow onwards.

**Comment by simonw** [comment]
Need to update https://www.pillarpointstewards.com/shifts/ too - which has an "Upcoming shifts" header.

For the moment I'm going to change that header to just say "All shifts" and leave it at that. We may decide to add more pages for past events in the future - and probably a user profile page too.
