### ISSUE TITLE
SVG of tide on shift page

### ISSUE THREAD

**Issue by natbat** [natbat/pillarpointstewards#44]
<img width="587" alt="Screen Shot 2022-04-02 at 12 18 12 PM" src="https://user-images.githubusercontent.com/72973/161397975-8ccc989e-a4c4-43e6-92c6-94f1b3c7922d.png">

See pattern portfolio: https://www.pillarpointstewards.com/patterns/

https://github.com/natbat/pillarpointstewards/blob/fff5f2de5cfcef85a143aa1a06753634d55cd203/pillarpointstewards/templates/patterns.html#L179-L208

**Comment by simonw** [comment]
Here's the code in Rocky Beaches that creates these: https://github.com/natbat/rockybeaches/blob/0c776a3becd77cc204ff9ac4aaf3525bf234f85b/plugins/template_vars.py#L103-L180 - to populate `svg_points`

And then this in the template: https://github.com/natbat/rockybeaches/blob/81e4e2507fc557bfb838cc55ac40904ec1785690/templates/row-data-places.html#L93-L115

```html+jinja
          <div class="day-view wider" style="
            background: linear-gradient(90deg,
              #176AB8 0%,
              #97bcdf {{ tide_data.dawn_pct }}%,
              #d1e1f1 {{ tide_data.sunrise_pct }}%,
              #FFFFFF {{ tide_data.noon_pct }}%,
              #d1e1f1 {{ tide_data.sunset_pct }}%,
              #97bcdf {{ tide_data.dusk_pct }}%,
              #176AB8 100%
            );
          ">
            <svg style="width: 100%; height: 60px; opacity: 0.5" viewBox="0 -2 240 104" preserveAspectRatio="none">
              <polyline fill="none" stroke="#176AB8" stroke-width="2"
                points="{{ tide_data.svg_points }}"
              />
            </svg>
            {% for minima in tide_data.minimas %}
              <span class="minima{% if minima == tide_data.lowest_daylight_minima %} best-minima{% endif %}" style="left: {{ minima.time_pct }}%">
                <span class="time">{{ nice_time(minima.time) }}</span>
                <span class="depth">{{ "%.2f"|format(minima.feet) }}ft</span>
              </span>
            {% endfor %}
          </div>
```

**Comment by simonw** [comment]
And it runs this big SQL query: https://github.com/natbat/rockybeaches/blob/0c776a3becd77cc204ff9ac4aaf3525bf234f85b/plugins/template_vars.py#L7-L53

```sql
with previous_day_last_record as (
  select
    station_id,
    datetime,
    mllw_feet
  from
    tide_predictions
  where
    date("datetime") = date(:day, '-1 days')
    and "station_id" = :station_id
  order by
    datetime desc
  limit
    1
), next_day_first_record as (
  select
    station_id,
    datetime,
    mllw_feet
  from
    tide_predictions
  where
    date("datetime") = date(:day, '1 days')
    and "station_id" = :station_id
  order by
    datetime
  limit
    1
)
select * from previous_day_last_record
  union
select * from next_day_first_record
  union
select
  station_id,
  datetime,
  mllw_feet
from
  tide_predictions
where
  date("datetime") = :day
  and "station_id" = :station_id
order by
  station_id,
  datetime
```

`station_id` is 9414131 - https://www.rockybeaches.com/data?sql=select+station_id%2C+slug+from+places+order+by+slug+limit+101

Here's a working link for a day with a shift - 19th April 2022:

https://www.rockybeaches.com/data?sql=with+previous_day_last_record+as+%28%0D%0A++select%0D%0A++++station_id%2C%0D%0A++++datetime%2C%0D%0A++++mllw_feet%0D%0A++from%0D%0A++++tide_predictions%0D%0A++where%0D%0A++++date%28%22datetime%22%29+%3D+date%28%3Aday%2C+%27-1+days%27%29%0D%0A++++and+%22station_id%22+%3D+%3Astation_id%0D%0A++order+by%0D%0A++++datetime+desc%0D%0A++limit%0D%0A++++1%0D%0A%29%2C+next_day_first_record+as+%28%0D%0A++select%0D%0A++++station_id%2C%0D%0A++++datetime%2C%0D%0A++++mllw_feet%0D%0A++from%0D%0A++++tide_predictions%0D%0A++where%0D%0A++++date%28%22datetime%22%29+%3D+date%28%3Aday%2C+%271+days%27%29%0D%0A++++and+%22station_id%22+%3D+%3Astation_id%0D%0A++order+by%0D%0A++++datetime%0D%0A++limit%0D%0A++++1%0D%0A%29%0D%0Aselect+*+from+previous_day_last_record%0D%0A++union%0D%0Aselect+*+from+next_day_first_record%0D%0A++union%0D%0Aselect%0D%0A++station_id%2C%0D%0A++datetime%2C%0D%0A++mllw_feet%0D%0Afrom%0D%0A++tide_predictions%0D%0Awhere%0D%0A++date%28%22datetime%22%29+%3D+%3Aday%0D%0A++and+%22station_id%22+%3D+%3Astation_id%0D%0Aorder+by%0D%0A++station_id%2C%0D%0A++datetime&station_id=9414131&day=2022-04-19

**Comment by simonw** [comment]
That code also calculates sunrise/sunset like this:
```python
        location_info = LocationInfo(
            place["address"],
            "",
            place["time_zone"],
            place["latitude"],
            place["longitude"],
        )
        tz = pytz.timezone(place["time_zone"])
        astral_info = sun.sun(location_info.observer, date=day)
```
I have those values stored separately so I could use the stored ones instead.

**Comment by simonw** [comment]
I only need a subset of the data though, considering this image:

![image](https://user-images.githubusercontent.com/9599/161403148-6d22e870-c0ce-4132-a863-2226d78389ee.png)

I need:

- Tide prediction every six minutes for the whole day
- The lowest tide that happens during the shift - we have this as `shift.mllw_feet` and `shift.lowest_tide`
- Sunrise/sunset/dawn/dusk/noon to help draw the gradient
- The shift start and end times

**Comment by simonw** [comment]
Also these two images:

- https://raw.githubusercontent.com/natbat/rockybeaches/main/static/stars-left.png
- https://raw.githubusercontent.com/natbat/rockybeaches/main/static/stars-right.png

**Comment by simonw** [comment]
I want the tide predictions in the local database, to avoid having to make an API call out to Rocky Beaches (which might have a slow-start if it's not had traffic in a while).

I only need them for the day that have shifts though.

**Comment by simonw** [comment]
Here's the script that fetches data from NOAA: https://github.com/natbat/rockybeaches/blob/0c776a3becd77cc204ff9ac4aaf3525bf234f85b/fetch_noaa_tide_times.py

It's actually pretty simple:

```python
def fetch_predictions(station_id):
    yesterday = datetime.date.today() - datetime.timedelta(days=1)
    end_date = yesterday + datetime.timedelta(days=365)
    url = "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?" + urlencode(
        {
            "begin_date": yesterday.strftime("%Y%m%d"),
            "end_date": end_date.strftime("%Y%m%d"),
            "product": "predictions",
            "station": station_id,
            "datum": "mllw",
            "time_zone": "lst_ldt",
            "units": "english",
            "format": "json",
        }
    )
    response = httpx.get(url)
    return response.json()["predictions"]


def fetch_noaa_tide_times(filepath):
    db = sqlite_utils.Database(filepath)
    tide_predictions = db.table("tide_predictions", pk=("station_id", "datetime"))
    station_ids = set()
    for place in db["places"].rows:
        if place["station_id"]:
            station_ids.add(place["station_id"])
    for station_id in station_ids:
        predictions = fetch_predictions(station_id)
        with db.conn:
            tide_predictions.insert_all(
                (
                    {
                        "station_id": station_id,
                        "datetime": p["t"],
                        "mllw_feet": float(p["v"]),
                    }
                    for p in predictions
                ),
                replace=True,
            )
```

**Comment by simonw** [comment]
Here's that raw URL for the next 365 days at Pillar Point:

https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?begin_date=20220401&end_date=20230401&product=predictions&station=9414131&datum=mllw&time_zone=lst_ldt&units=english&format=json

Generated using:

```python
import datetime
from urllib.parse import urlencode

def fetch_predictions(station_id="9414131"):
    yesterday = datetime.date.today() - datetime.timedelta(days=1)
    end_date = yesterday + datetime.timedelta(days=365)
    url = "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?" + urlencode(
        {
            "begin_date": yesterday.strftime("%Y%m%d"),
            "end_date": end_date.strftime("%Y%m%d"),
            "product": "predictions",
            "station": station_id,
            "datum": "mllw",
            "time_zone": "lst_ldt",
            "units": "english",
            "format": "json",
        }
    )
    return url

print(fetch_predictions())
```

**Comment by simonw** [comment]
Can import them using `./manage.sh shell_plus` and then:

```python
TidePrediction.populate_for_station(9414131)
```

**Comment by simonw** [comment]
The Astral bit:
```pycon
>>> from astral import LocationInfo, sun
>>> LocationInfo(latitude=37.495182, longitude=-122.5003437)
LocationInfo(name='Greenwich', region='England', timezone='Europe/London', latitude=37.495182, longitude=-122.5003437)
>>> loc = LocationInfo(latitude=37.495182, longitude=-122.5003437, timezone='America/Los_Angeles')
LocationInfo(name='Greenwich', region='England', timezone='America/Los_Angeles', latitude=37.495182, longitude=-122.5003437)
>>> import datetime
>>> sun.sun(loc.observer, date=datetime.date(2022, 5, 1))
{'dawn': datetime.datetime(2022, 5, 1, 12, 46, 11, 885342, tzinfo=<UTC>), 'sunrise': datetime.datetime(2022, 5, 1, 13, 14, 50, 245907, tzinfo=<UTC>), 'noon': datetime.datetime(2022, 5, 1, 20, 7, 9, tzinfo=<UTC>), 'sunset': datetime.datetime(2022, 5, 2, 2, 59, 52, 223876, tzinfo=<UTC>), 'dusk': datetime.datetime(2022, 5, 2, 3, 28, 36, 422981, tzinfo=<UTC>)}
```

**Comment by simonw** [comment]
Need to make sure running this multiple times doesn't add duplicates. I can do that with a unique together constraint on `station_id` and `dt`.

**Comment by simonw** [comment]
That unique together constraint worked:
```pycon
>>> TidePrediction.populate_for_station(9414131)
TidePrediction.objects.count()
>>> TidePrediction.objects.count()
87830
>>> TidePrediction.populate_for_station(9414131)
>>> TidePrediction.objects.count()
87830
```

**Comment by simonw** [comment]
That time running it in production worked:

```
(pillarpointstewards) pillarpointstewards % fly ssh console -a pillarpointstewards
Connecting to top1.nearest.of.pillarpointstewards.internal... complete
# /app/manage.py shell_plus
...
>>> TidePrediction.populate_for_station(9414131)
>>> TidePrediction.objects.count()
87830
>>> 
```

**Comment by simonw** [comment]
https://www.pillarpointstewards.com/admin/tides/tideprediction/ now shows the data:

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/9599/161404988-f4170b03-77a0-4e42-aae6-ee7e16f29393.png">

**Comment by simonw** [comment]
I'm going to create a `/debug/tide-times/2022-04-01/` page which shows me just the tide times graphic to make it easier to hack on.

**Comment by simonw** [comment]
Work in progress demo: https://www.pillarpointstewards.com/debug/tide-times/2022-04-04/

**Comment by simonw** [comment]
Leaving this open until I've added tests - especially to confirm that days which we do not have tide data don't break.

**Comment by simonw** [comment]
https://www.pillarpointstewards.com/shifts/189/

![Uploading B19C3461-3BCC-4D5C-963C-5A778D08B78B.jpeg…]()
