### ISSUE TITLE
Manage upcoming shifts page

### ISSUE THREAD

**Issue by simonw** [natbat/pillarpointstewards#74]
This page will let program coordinators edit existing shifts, add shifts manually and add shifts using a new version of the calculator from https://observablehq.com/@natbat/tidepool-shift-calculator-v2

Still needed:

- [x] #102
- [x] #103
- [x] #104
- [x] #105

**Comment by simonw** [comment]
URL will be `/programs/pillarpoint/manage-shifts/`

**Comment by natbat** [comment]
![53A29CD0-90A1-4B2D-943C-51DD355009E5](https://github.com/natbat/pillarpointstewards/assets/72973/a6750117-a3b6-4da5-8236-31068454fd7d)
![50AAD3FA-F2A8-4A92-8CCF-C2F32BA6A7F0](https://github.com/natbat/pillarpointstewards/assets/72973/f1616421-cf68-473e-aaff-b2fa755dd83c)
![05137270-A496-42AA-B98E-85A6B0D651BA](https://github.com/natbat/pillarpointstewards/assets/72973/53cb62a4-a3bd-4604-8c4d-9c5ae516612f)

**Comment by simonw** [comment]
The real magic of the Observable notebook is this SQL query: https://www.rockybeaches.com/data?station_id=9414131&tide=-1&tide_weekends=0&sunlight_place=pillar-point&sql=%0Awith%20inner%20as%20(%0A%20%20select%0A%20%20%20%20datetime%2C%0A%20%20%20%20substr(datetime%2C%200%2C%2011)%20as%20date%2C%0A%20%20%20%20mllw_feet%2C%0A%20%20%20%20lag(mllw_feet)%20over%20win%20as%20previous_mllw_feet%2C%0A%20%20%20%20lead(mllw_feet)%20over%20win%20as%20next_mllw_feet%0A%20%20from%0A%20%20%20%20tide_predictions%0A%20%20%20%20join%20sunrise_sunset%20on%20place%20%3D%20%3Asunlight_place%0A%20%20%20%20and%20day%20%3D%20date(datetime)%0A%20%20where%0A%20%20%20%20case%0A%20%20%20%20%20%20when%20strftime(%27%25w%27%2C%20datetime)%20in%20(%270%27%2C%20%276%27)%20then%20mllw_feet%20%3C%20%3Atide_weekends%0A%20%20%20%20%20%20else%20mllw_feet%20%3C%20%3Atide%0A%20%20%20%20end%0A%20%20%20%20and%20station_id%20%3D%20%3Astation_id%0A%20%20%20%20and%20datetime%20%3E%3D%20date()%0A%20%20%20%20and%20time(datetime)%20%3E%20dawn%0A%20%20%20%20and%20time(datetime)%20%3C%20dusk%0A%20%20window%20win%20as%20(%0A%20%20%20%20order%20by%20datetime%0A%20%20)%0A%20%20order%20by%0A%20%20%20%20datetime%0A)%2C%0Alowest_tide_per_day%20as%20(%0A%20%20select%0A%20%20%20%20date%2C%0A%20%20%20%20datetime%2C%0A%20%20%20%20mllw_feet%0A%20%20from%0A%20%20%20%20inner%0A%20%20where%0A%20%20%20%20mllw_feet%20%3C%3D%20previous_mllw_feet%0A%20%20%20%20and%20mllw_feet%20%3C%3D%20next_mllw_feet%0A)%0Aselect%0A%20%20min(datetime)%20as%20datetime%2C%0A%20%20mllw_feet%0Afrom%0A%20%20lowest_tide_per_day%0Agroup%20by%0A%20%20date%0Aorder%20by%0A%20%20date&_shape=array

```sql
with inner as (
  select
    datetime,
    substr(datetime, 0, 11) as date,
    mllw_feet,
    lag(mllw_feet) over win as previous_mllw_feet,
    lead(mllw_feet) over win as next_mllw_feet
  from
    tide_predictions
    join sunrise_sunset on place = :sunlight_place
    and day = date(datetime)
  where
    case
      when strftime('%w', datetime) in ('0', '6') then mllw_feet < :tide_weekends
      else mllw_feet < :tide
    end
    and station_id = :station_id
    and datetime >= date()
    and time(datetime) > dawn
    and time(datetime) < dusk
  window win as (
    order by datetime
  )
  order by
    datetime
),
lowest_tide_per_day as (
  select
    date,
    datetime,
    mllw_feet
  from
    inner
  where
    mllw_feet <= previous_mllw_feet
    and mllw_feet <= next_mllw_feet
)
select
  min(datetime) as datetime,
  mllw_feet
from
  lowest_tide_per_day
group by
  date
order by
  date
```
Explained by GPT-4:

> This SQL query seems to be working with a dataset that has information about tide predictions and sunrise/sunset timings for certain places. The primary objective seems to be to identify the lowest tide time within daylight hours for each day, subject to certain conditions, and particularly favoring certain conditions for weekends.
> 
> Let's break it down step by step:
> 
> 1. **Inner Subquery:**
>     - It takes records from the `tide_predictions` table and joins with `sunrise_sunset` on the place and day fields.
>     - It then extracts the date from the datetime field.
>     - It calculates the previous and next tide levels using the `LAG` and `LEAD` window functions.
>     - The WHERE conditions apply several filters:
>         - The tide should be below a certain threshold (`:tide` for weekdays and `:tide_weekends` for weekends).
>         - The station_id should match a parameter.
>         - The datetime should be from today onward.
>         - The tide time should be between dawn and dusk.
>   
> 2. **lowest_tide_per_day Subquery:**
>     - It takes records from the inner subquery.
>     - It then filters to identify tides that are lower than both their immediate preceding and succeeding tides, i.e., it finds local minima.
>   
> 3. **Main Query:**
>     - It aggregates records from the `lowest_tide_per_day` subquery by date.
>     - For each date, it identifies the earliest lowest tide time.
>     - It then sorts the results by date.
> 
> The final output is a dataset that has the earliest lowest tide time for each day (within daylight hours) that satisfies the given conditions. 
> 
> Do note that this approach assumes that there can be multiple low tides in a single day, but wants only the earliest one which is the lowest. It also assumes that tide times near dawn or dusk are not wanted, which is why there's a filtering condition to keep tides strictly between dawn and dusk.

**Comment by simonw** [comment]
Progress so far:

<img width="1146" alt="image" src="https://github.com/natbat/pillarpointstewards/assets/9599/3aa1bd68-3351-44de-b145-031a4d76e07d">

**Comment by natbat** [comment]
![0672A246-762C-4B99-B6E4-4B8628F7CF7A](https://github.com/natbat/pillarpointstewards/assets/72973/574c4958-ebca-4942-81dc-475b367ed3e4)

**Comment by simonw** [comment]
Next step: get the shift calculator working.
